In [3]:
from ydata_profiling import ProfileReport
import pandas as pd
from sklearn.datasets import fetch_openml

In [5]:
data = fetch_openml(name="Boston", as_frame=True)
data

/home/vijeth/learning/ml-lab/ml-lab/lib/python3.11/site-packages/sklearn/datasets/_openml.py:323: UserWarning: Multiple active versions of the dataset matching the name boston exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=531
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=853

  warn(warning_msg)

{'data':         CRIM    ZN  INDUS CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
 0    0.00632  18.0   2.31    0  0.538  ...    1  296.0     15.3  396.90   4.98
 1    0.02731   0.0   7.07    0  0.469  ...    2  242.0     17.8  396.90   9.14
 2    0.02729   0.0   7.07    0  0.469  ...    2  242.0     17.8  392.83   4.03
 3    0.03237   0.0   2.18    0  0.458  ...    3  222.0     18.7  394.63   2.94
 4    0.06905   0.0   2.18    0  0.458  ...    3  222.0     18.7  396.90   5.33
 ..       ...   ...    ...  ...    ...  ...  ...    ...      ...     ...    ...
 501  0.06263   0.0  11.93    0  0.573  ...    1  273.0     21.0  391.99   9.67
 502  0.04527   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   9.08
 503  0.06076   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   5.64
 504  0.10959   0.0  11.93    0  0.573  ...    1  273.0     21.0  393.45   6.48
 505  0.04741   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
 0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
 1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
 2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
 3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
 4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2
 ..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...   ...
 501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67  22.4
 502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08  20.6
 503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64  23.9
 504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48  22.0
 505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://api.openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'minio_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [6]:
df = pd.DataFrame(data.data, columns=data.feature_names)
df["TARGET"] = data.target
df

        CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  TARGET
0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98    24.0
1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14    21.6
2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03    34.7
3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94    33.4
4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33    36.2
..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...     ...
501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67    22.4
502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08    20.6
503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64    23.9
504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48    22.0
505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88    11.9

[506 rows x 14 columns]

In [7]:
profile = ProfileReport(df)
profile.to_file(output_file="boston_housing_profile.html")

100%|██████████| 14/14 [00:00<00:00, 137840.98it/s]:00, 64.95it/s, Describe variable: TARGET]
Summarize dataset: 100%|██████████| 167/167 [00:06<00:00, 27.21it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.60s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.58s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 92.34it/s]